# Generated by Django 3.0.5 on 2020-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('country', models.TextField(primary_key=True, serialize=False, verbose_name='country')),
                ('new_cases', models.TextField(verbose_name='new_cases')),
                ('active_cases', models.IntegerField(verbose_name='active_cases')),
                ('critical_cases', models.IntegerField(verbose_name='critical_cases')),
                ('recovered_cases', models.IntegerField(verbose_name='recovered_cases')),
                ('total_cases', models.IntegerField(verbose_name='total_cases')),
                ('new_deaths', models.TextField()),
                ('total_deaths', models.IntegerField(verbose_name='total_deaths')),
                ('total_tests', models.IntegerField(verbose_name='total_tests')),
                ('day', models.TextField(verbose_name='day')),
                ('time', models.TextField(verbose_name='time')),
            ],
        ),
    ]
